// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: helloworld.proto

package proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_HelloRequest_Name = regexp.MustCompile(`^[z]{2,5}$`)

func (this *HelloRequest) Validate() error {
	if !_regex_HelloRequest_Name.MatchString(this.Name) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^[z]{2,5}$"`, this.Name))
	}
	return nil
}
func (this *HelloReply) Validate() error {
	return nil
}
